MO zadania zestaw 1

zadanie 1: Napisz jednoargumentową funkcję w Pythonie, która będzie zwracać true, gdy liczba podana jako argument będzie pierwsza lub false w przeciwnym wypadku. Używając tej funkcji napisz list comprehention, które wygeneruje tablicę liczb pierwszych mniejszych od 100. Wskazówka: range(100) zwóci generator liczb od 0 do 99 włącznie.

In [14]:
def isPrime(number):
    flag = True

    if number > 1:
        for i in range(2, number):
            if (number % i) == 0:
                flag = False

                break
    return flag

In [15]:
print({ x for x in range(100) if isPrime(x) == True})

{0, 1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97}


zadanie 2: Napisz funkcję, która dla danej tablicy numpy'owej zwróci drugą największą wartość. (Mogą się przydać takie funkcje, jak np.max, czy np.where)

In [4]:
import numpy as np
array = np.array([3,6,4,9,33,55])

def secondMax():
    array = np.array([3,6,4,9,33,55])
    x = np.max(array)
    index = np.where(array == x)
    array = np.delete(array, index)
    result = np.max(array)
    print(result)
    
#different methode
i = np.unique(array)[-2]

In [5]:
secondMax()
print(i)

33
33


zadanie 3: Napisz funkcję używającą numpy, która obliczy przybliżone odwrócenie macierzy korzystając z np.linalg.solve, które służy do rozwiązywania układów równań liniowych i macierzowych.

In [10]:
import numpy as np
A = np.array([[1,-2,3],[-1,1,5],[-2,-1,1]])
B = np.linalg.inv(A)
print(np.linalg.det(B))

0.030303030303030304


zadanie 4: Używając broadcastingu napisz funkcję przyjmującą argument n, która wygeneruje tabliczkę mnożenia n na n w postaci tablicy numpy'owej.

In [8]:
import numpy as np


In [13]:
n = int(input("podaj n"))
m=np.arange(1,n)
print(m)
q=m.reshape(-1,1)
print(q)
print(m*q)

podaj n5
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
